name: mmoDamage
version: ${releaseVersion}.${buildNumber}
description: Provides an easy interface for damage control.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Damage.MMODamage
depend: [Spout, mmoCore]
